import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "antd-mobile/es/global";
import StoreProvider from "@/context/storeProvider";
import styles from "./layout.module.css";
import Login from "@/app/auth/login";
import IndexedDBHelper from '@/helpers/indexedDBHelper';

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const init = () => {
    const dbName = 'dcwallet';
    const storeConfigs = [
      
    ];
    const version = 1;
    new IndexedDBHelper(dbName, storeConfigs, version = 1)
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.container}>
          <StoreProvider>
            <Login />
            {children}
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
